class ConfigValue:
    SPRAY_WPI_NUM = 4
    VALVE_WPI_NUM = 5
    MAX_AUTO_SPRAY_TIME = 30
    MIN_AUTO_SPRAY_TIME = 5
    MAX_AUTO_CYCLE_TIME = 10
    MIN_AUTO_CYCLE_TIME = 1
    MAX_SPRAY_TIME = 10.0
    MIN_SPRAY_TIME = 1.0
    MAX_DETECT_DISTANCE = 3.0
    MIN_DETECT_DISTANCE = 0.5
    VALVE_ON_TIME = 1.5